Discussion/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.contrib.auth import views as auth_views
from . import views
app_name='Discussion'
urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^(?P<pk>\d+)/$',views.post_details,name='post_details'),
	url(r'^Post_it/',views.Post_it,name='Post_it'),
]

hackathon/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^signup/',views.signup,name='signup'),
    url(r'^discussion/',include('Discussion.urls',namespace='Discussion')),
    url(r'^home/',views.home,name='home'),
]

Discussion/models.py
from django.db import models
from django.contrib.auth.models import User

#class Tag(models.Model):
#	title=models.CharField(max_length=255,unique=True)
#	def __str__(self):
#		return self.title
postags=[('','-----'),('1','Guitar'),('2','Blockchain'),('3','Flute')]
class Post(models.Model):
	title=models.CharField(max_length=255)
	Author=models.ForeignKey('auth.User',on_delete=models.CASCADE, null=True)
	body=models.TextField()
	posted=models.DateField(db_index=True, auto_now_add=True)
	tags=models.CharField(max_length=255,choices=postags,null=True)
	def __str__(self):
		return self.title

class Comment(models.Model):
	ctor=models.ForeignKey('auth.User',on_delete=models.CASCADE, null=True)
	cdate=models.DateField(db_index=True, auto_now_add=True)
	cbody=models.TextField()
	cpost=models.ForeignKey('Post',on_delete=models.CASCADE, null=True)

	def __str__(self):
		return str(self.ctor)+str(self.cpost)+str(self.cbody)
	

Discussion/forms.py
from django import forms
from django.contrib.auth.models import User,Group
from .models import Post,Comment
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','body','tags']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['cbody']

hackathon/forms.py
from django import forms
from django.contrib.auth.models import User,Group
class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    username = forms.CharField(max_length=30, required=True)
    first_name = forms.CharField(max_length=30, required=True)#inbuilt user field
    last_name = forms.CharField(max_length=30, required=True)#inbuilt user field
    email=forms.EmailField(required=True)#inbuilt user field
    class Meta:
        model = User
        fields = ['first_name','last_name','username','email','password',]

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.username=self.cleaned_data["username"]
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

Discussion/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .forms import PostForm,CommentForm
from .models import Post, Comment 
def home(request):
	posts=Post.objects.all()
	return render(request,'Discussion/home.html',{'posts':posts})

def post_details(request,pk):
	current_post=get_object_or_404(Post,pk=pk)
	cts=Comment.objects.filter(cpost=current_post)
	form = CommentForm(request.POST)
	if form.is_valid():
		print("valid")
		comment = form.save(commit=False)
		cbody = form.cleaned_data['cbody']
		comment.ctor=request.user
		comment.cpost=current_post
		comment.save()
		print("abcd")
		print(comment)
		return redirect('Discussion:post_details',pk=pk)
	print(cts)
	return render (request,'Discussion/details.html',{'current_post': current_post,
														'cts' : cts,
														'forms': form})

def Post_it(request):
	form = PostForm(request.POST)
	if form.is_valid():
		print("valid")
		post = form.save(commit=False)
		title = form.cleaned_data['title']
		body = form.cleaned_data['body']
		post.Author=request.user
		post.save()
		return redirect('Discussion:home')
	return render(request, 'Discussion/Post_it.html',{'form':form})

Profile/views.py
from django.shortcuts import render

# Create your views here.

hackathon/views.py
from django.shortcuts import render
from django.http import HttpResponse
from hackathon.forms import RegistrationForm
from django.contrib.auth import authenticate, logout,login
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
	return render(request,'registration/index.html')


def signup(request):
	form = RegistrationForm(request.POST)
	if form.is_valid():
		print("valid")
		user = form.save(commit=False)
		username = form.cleaned_data['username']
		password = form.cleaned_data['password']
		user.set_password(password)
		user.save()
		user = authenticate(username=username, password=password)
		if user is not None:
			print(user)
			if user.is_active:
				print(user)
				login(request,user)
				return render(request, 'home/home.html')

	return render(request, 'registration/signup.html',{'form':form})

@login_required
def home(request):
	return render(request,'home/home.html')

Discussion/templates/Discussion/Post_it.html
<html>
<head>
  <title>InterestDotMeet</title>
<!--static folder inside every app should have a folder inside it with app name(maekes easy to locate from which app this style sheet is called) reason to have folder is since static root track asked file from each app in alphabatic order so if to static file have same path after static folder that file from other app may come which might not be your need so better to have a good organisation-->
</head>
<body>
  <header>
	<h1>InterestDotMeet</h1>
	{% if user.is_authenticated %}
	  You are signed in as <strong>{{ user.username }}</strong> /

	  <a href="{% url 'logout'%}?next=accounts/">logout</a>
	{% endif %}
	<hr>
  </header>
  <main>
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">Post</button>
  </form>
  </main>
</body>
</html>

Discussion/templates/Discussion/details.html
<html>
	<body>
		{{current_post.body}}
		{{current_post.Author}}
		{{current_post.posted}}
		{% for comment in cts %}
		{{comment.cbody}}
		{%endfor%}
		<form method="post">
	{% csrf_token %}
	{{ forms.as_p }}
	<button type="submit">Post</button>
  </form>

	</body>
</html>

Discussion/templates/Discussion/home.html
<html>
	<body>
		<a href="{% url 'Discussion:Post_it' %}">POST</a>
		{% for post in posts%}
		<a href="{%url 'Discussion:post_details' pk=post.pk %}">{{post.title}}</a>
		{%endfor%}
	</body>
</html>

hackathon/templates/home/base.html
{% load static %}
<html>
<head>
  <title>InterestDotMeet</title>
  <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
  <link href ="{% static 'style2.css' %}" rel="stylesheet"/>
<!--static folder inside every app should have a folder inside it with app name(maekes easy to locate from which app this style sheet is called) reason to have folder is since static root track asked file from each app in alphabatic order so if to static file have same path after static folder that file from other app may come which might not be your need so better to have a good organisation-->
</head>
<body>
  <header>
    <h1>InterestDotMeet</h1>
    {% if user.is_authenticated %}
      You are signed in as <strong>{{ user.username }}</strong> /

      <a href="{% url 'logout'%}?next=accounts/">logout</a>
    {% endif %}
    <hr>
  </header>
  <main>
    {% for message in messages %}
      <p style="color: {% if message.tags == 'success' %}green{% elif message.tags == 'error' %}red{% endif %}">
        {{ message }}
      </p>
    {% endfor %}
    <!--better to use base_content in place of content it is helpfull in case of nested extention and inclusion of html files using block tag of django-->
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

hackathon/templates/home/home.html
<html>
<body>Hello {{user.username}}</body>
<strong>{{ user.username }}</strong> 
<a href="{% url 'logout'%}?next=/">logout</a>

</html>